spring:
  datasource:
    url: jdbc:mysql://localhost:3306/voucher_mgmt
    username: root
    password: root1234!
    type: com.zaxxer.hikari.HikariDataSource
  messages:
    basename: messages
    encoding: UTF-8

  mvc:
    hiddenmethod:
      filter:
        enabled: true