spring:
  profiles:
    active: local-file

---

spring.config.activate.on-profile: local-file
filedb:
  blacklist: filedb/blacklist.csv
  voucher: filedb/voucher.csv

---

spring.config.activate.on-profile: local-memory

---

spring.config.activate.on-profile: dev