spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/voucher_w2?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8

#    jdbc:mysql://localhost:3306/db_name?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root1234
