classpath.customer-blacklist: customer_blacklist.csv

---
spring:
  config:
    activate:
      on-profile: "dev"

classpath.voucher-storage: classpath:voucher_storage.txt

---
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${username}
      password: ${password}
      jdbc-url: ${url}
  mvc:
    hiddenmethod:
      filter:
        enabled: true