spring:
  config:
    activate:
      on-profile: dev
---

spring:
  profiles:
    group:
      dev:
        - console-logging
        - file-logging
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_mgmt
    username: root
    password: root1234!

path:
  voucher: voucher.txt
  blacklist: blacklist.csv

---

spring:
  profiles:
    group:
      prod:
        - file-logging

path:
  blacklist: blacklist.csv

---