spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:mysql://localhost:3306/spring_basic
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
