spring:
  profiles:
    active: file

saveType: "File Management"
voucherStoragePath: "src/main/resources/storage/voucherStorage.txt"
blackListStoragePath: "src/main/resources/storage/blacklist.csv"

---

spring:
  profiles:
    active: memory

saveType: "Memory Management"
blackListStoragePath: "src/main/resources/storage/blacklist.csv"

---

spring:
  profiles:
    active: jdbc
  datasource:
    username: sa
    url: jdbc:h2:tcp://localhost/~/vouchers
blackListStoragePath: "src/main/resources/storage/blacklist.csv"

