
---

spring:
  config:
    activate:
      on-profile: dev
file:
  customer:
    file-path: src/customer_blacklist.csv
  voucher:
    file-path: src/voucher_memory.csv


---

spring:
  config:
    activate:
      on-profile: local
file:
  customer:
    file-path: src/customer_blacklist.csv
  voucher:
    file-path: src/voucher_memory.csv



