#spring:
#  profiles:
#    group:
#      "dev":""
#      "prod":""

---
spring:
  config:
    activate:
      on-profile: "dev"

voucher:
  path: "./voucher_list.csv"
  append: true

logging:
  file:
    name: "./log/voucher_manager.log"
---
spring:
  config:
    activate:
      on-profile: "default"

voucher:
  path: "./voucher_list.csv"
  append: true
logging:
  file:
    name: "./log/voucher_manager.log"