spring.config.activate.on-profile: default
command:
  write: system
  read: scanner
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/voucher
    username: "qwe"
    password: "qwe123"
---

spring.config.activate.on-profile: dev
command:
  write: system
  read: console

---

spring.config.activate.on-profile: local
command:
  write: system
  read: buffer

---

spring.config.activate.on-profile: test
command:
  write: system
  read: scanner

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:voucher
    username: test
    password:
