spring:
  datasource:
    url: jdbc:mysql://localhost/dev_test?characterEncoding=UTF-8&serverTimezone=UTC
    username: yeon
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:test-data.sql