spring:
  profiles:
    active: deploy

---

spring:
  profiles: dev

file:
  path:
    blacklist: customer_blacklist.csv

---

spring:
  profiles: local

file:
  path:
    blacklist: customer_blacklist.csv
    voucher: voucher_db.txt

---

spring:
  profiles: deploy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/voucher_management?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: xkakak142

file:
  path:
    blacklist: customer_blacklist.csv