spring:
  profiles:
    default: file
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: file
csv:
  file:
    voucher:
      path: "src/main/resources/vouchers.csv"
    customer:
      blacklist_path: "src/main/resources/customer_blacklist.csv"
  separator: ","
