files:
  customer-blacklist: src/main/resources/data/customer_blacklist.csv
  voucher-record: src/main/resources/data/voucher_record.csv

---

spring:
  profiles:
    active: release

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:tcp://localhost/~/mission1
    username: sa
    password: 5643

#logging:
#  level:
#    org:
#      springframework:
#        level: debug