spring.config.activate.on-profile: local-file
filedb:
  path: src/main/resources/filedb
  blacklist: blacklist.csv
  voucher: voucher.csv

---

spring.config.activate.on-profile: local-memory

---

spring.config.activate.on-profile: dev