logging:
  config:
    classpath: logback.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/voucherproject?useSSL=false
    username: spring4
    password: spring4
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always