
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/voucher_mgmt
    username: root
    password: surin1119
  config:
    activate:
      on-profile: jdbc

---
spring:
  profiles:
    active: dev