settings:
  version: "v2.1"
  description: "어려워잌ㅋ"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/voucher_system
    username: root
    password: root1234!
    driver-class-name: com.mysql.cj.jdbc.Driver