version: "1.0"
description: "File"


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/voucher_management?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:

  sql:
    init:
      platform: mysql
      mode: always
