settings:
  version: "v2.1"
  description: "어려워잌ㅋ"

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    bean: jasyptStringEncryptor
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100
spring:
  datasource:
    url: ENC(VnPYjuns7r1IZCXS4/d9evC0QDwDw6pORpvqUVvxhoA21nkdEy0x3VxPcBkNwbC+)
    username: ENC(ariKMyHoKiZ0ULrSg9YatA==)
    password: ENC(bw3uZYpzlOJsdpIjFQzSgDENsaR0PsIW)
    driver-class-name: com.mysql.cj.jdbc.Driver
