spring:
  profiles:
    active: dev
csv:
  voucher:
    file-name: voucherList_sample.csv
    path: src\\main\\resources
  member:
    file-name: customer_blacklist_sample.csv
    path: src\\main\\resources