spring.config.activate.on-profile: local-file
voucher:
  path: src/main/resources/filedb
  blacklist: blacklist.csv
  name: voucher.csv

---

spring.config.activate.on-profile: local-memory

---

spring.config.activate.on-profile: dev