system:
  blacklist:
    blacklistAllow: true
    blacklistShowId: true
  voucher:
    maximum-fixed-amount: 1000

spring:
  datasource:
    url: jdbc:mysql://localhost:3380/voucher-management
    username: root
    password: root