spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev

file:
  voucher:
    file-path: src/main/resources/voucher_file.csv

---
file:
  blacklist:
    file-path: src/main/resources/blacklist.csv

---
spring:
  config:
    activate:
      on-profile: jdbc

  datasource:
    url: jdbc:mysql://localhost/voucher_db
    username: admin
    password: admin1234