voucher:
  file:
    path: ./storage/voucherFile.csv

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/VOUCHER_MANAGEMENT_DATABASE?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234!