# FileBlackListProperties 라는 class getFileName, getFilePath
# FileVoucherProperties 라는 class getFileName, getFilePath

file:
  customer-black-list:
    name: customer_blacklist.csv
    path: resources/

  voucher-list:
    name: voucherList.txt
    path: resources/
---

spring:
  config:
    activate:
      on-profile: release
  datasource:
    url: ${datasource.url} # jdbc:mysql://localhost:3306/VoucherManagementApplication
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 암호화 어떻게 해야 하나요?