black-list:
  csv-file-name: customer_blacklist.csv
  path: src\main\resources\customer_blacklist.csv

---

spring:
  config:
    activate:
      on-profile: prod

voucher:
  file-name : vouchers.csv
  path: src\main\resources\vouchers.csv


---