db:
  path: src/main/resources/db
  blacklist:
    db_name: customer_blacklist.csv
  voucher:
    db_name: voucher_db.csv

spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: prod

