spring.config.activate.on-profile: local

---

spring.config.activate.on-profile: file

voucher:
  path: src/main/resources/voucherFileRepository.txt

sequence:
  path : src/main/resources/voucherIdSequence

---

spring.config.activate.on-profile: dataBase

spring:
  datasource:
    url: jdbc:mysql://localhost/voucher_program
    username: root
    password: root1234!