---
spring:
  config:
    activate:
      on-profile: "dev"

voucher.path: "./VoucherList.csv"
voucher.canAppand: true
logging:
  level: warn
---
spring:
  config:
    activate:
      on-profile: "default"

voucher.path: "./VoucherList.csv"
voucher.canAppand: true